---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'Puede activar el almacenamiento de escritura única y lectura múltiple (WORM) en un sistema Cloud Volumes ONTAP para conservar los archivos en forma no modificada durante un período de retención específico. El almacenamiento WORM de cloud cuenta con tecnología SnapLock, lo que significa que los archivos WORM están protegidos a nivel de archivo.' 
---
= Almacenamiento WORM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puede activar el almacenamiento de escritura única y lectura múltiple (WORM) en un sistema Cloud Volumes ONTAP para conservar los archivos en forma no modificada durante un período de retención específico. El almacenamiento WORM de cloud cuenta con tecnología SnapLock, lo que significa que los archivos WORM están protegidos a nivel de archivo.

La función WORM está disponible para su uso con su propia licencia BYOL y suscripciones de mercado para sus licencias sin coste adicional. Póngase en contacto con su representante de ventas de NetApp para agregar WORM a su licencia actual.



== Cómo funciona el almacenamiento WORM

Una vez que se ha comprometido un archivo con el almacenamiento WORM, no se puede modificar, ni siquiera después de que haya caducado el período de retención. Un reloj a prueba de manipulaciones determina cuándo ha transcurrido el período de retención de un archivo WORM.

Una vez transcurrido el período de retención, es responsable de eliminar los archivos que ya no se necesiten.



== Activación del almacenamiento WORM

La forma de activar el almacenamiento WORM depende de la versión de Cloud Volumes ONTAP que utilice.



=== Versión 9.10.1 y posterior

A partir de Cloud Volumes ONTAP 9.10.1, tiene la opción de habilitar o deshabilitar WORM en el nivel de volumen.

Cuando crea un nuevo entorno de trabajo Cloud Volumes ONTAP, se le pedirá que habilite o deshabilite el almacenamiento WORM:

* Si activa el almacenamiento WORM al crear un entorno de trabajo, todos los volúmenes que cree desde BlueXP tienen WORM activado. Pero puede usar ONTAP System Manager o la interfaz de línea de comandos de ONTAP para crear volúmenes que tengan WORM deshabilitado.
* Si deshabilita el ALMACENAMIENTO WORM al crear un entorno de trabajo, cada volumen que cree desde BlueXP , ONTAP System Manager o la interfaz de línea de comandos de ONTAP tendrá WORM deshabilitado.




=== Versión 9.10.0 y anteriores

Puede activar el almacenamiento WORM en un sistema Cloud Volumes ONTAP cuando crea un nuevo entorno de trabajo. Todos los volúmenes que cree desde BlueXP tienen WORM activado. No se puede deshabilitar el almacenamiento WORM en volúmenes individuales.



== Conserva archivos en WORM

Puede utilizar una aplicación para confirmar los archivos a WORM a través de NFS o CIFS, o utilizar la interfaz de línea de comandos de ONTAP para confirmar automáticamente los archivos a WORM. También puede utilizar un archivo WORM ampliable para conservar datos que se escriben de forma incremental, como la información de registro.

Después de activar el almacenamiento WORM en un sistema Cloud Volumes ONTAP, debe utilizar la CLI de ONTAP para toda la gestión del almacenamiento WORM. Para obtener instrucciones, consulte http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["Documentación de ONTAP"^].



== Habilitar WORM en un entorno de trabajo Cloud Volumes ONTAP

Puede habilitar el ALMACENAMIENTO WORM al crear un entorno de trabajo de Cloud Volumes ONTAP en BlueXP . También puede habilitar WORM en un entorno de trabajo si no se habilita WORM en él durante su creación. Después de habilitarla, no se puede deshabilitar WORM.

.Acerca de esta tarea
* WORM es compatible con ONTAP 9.10,1 y versiones posteriores.
* ONTAP 9.11,1 y versiones posteriores es compatible con WORM con backup.


.Pasos
. En la página Lienzo, haga doble clic en el nombre del entorno de trabajo en el que desea habilitar WORM.
. En la pestaña Vista general, haga clic en el panel Características y luego haga clic en el icono del lápiz junto a *WORM*.
+
Si WORM ya está activado en el sistema, el icono de lápiz se desactivará.

. En la página *WORM*, establezca el período de retención para el reloj de cumplimiento del clúster.
+
Para obtener más información, consulte https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["Documentación de ONTAP: Inicialice el reloj de cumplimiento"^].

. Haga clic en *establecer*.


.Después de terminar
Puede verificar el estado de *WORM* en el panel de características. Una vez que se habilita WORM, la licencia de SnapLock se instala automáticamente en el clúster. Puede ver la licencia de SnapLock en System Manager de ONTAP.



== Eliminando ARCHIVOS WORM

Es posible eliminar ARCHIVOS WORM durante el período de retención mediante la función de eliminación con privilegios.

Para obtener instrucciones, consulte https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["Documentación de ONTAP"^] .



== WORM y la organización en niveles de los datos

Cuando crea un nuevo sistema Cloud Volumes ONTAP 9.8 o posterior, puede habilitar la organización en niveles de datos y el almacenamiento WORM juntos. Habilitar la organización en niveles de datos con el almacenamiento WORM permite organizar los datos en niveles en un almacén de objetos en el cloud.

Debe comprender lo siguiente sobre la habilitación de la organización en niveles de datos y el almacenamiento WORM:

* Los datos organizados en niveles en niveles en almacenamiento de objetos no incluyen la funcionalidad WORM de ONTAP. Para garantizar la funcionalidad WORM integral, deberá configurar los permisos de bucket correctamente.
* Los datos organizados en niveles en almacenamiento de objetos no llevan la funcionalidad WORM, lo que significa que, técnicamente, cualquier persona con acceso completo a bloques y contenedores puede eliminar los objetos organizados por niveles mediante ONTAP.
* Revertir o degradar a Cloud Volumes ONTAP 9.8 debe estar bloqueado después de habilitar WORM y organización en niveles.




== Limitaciones

* El almacenamiento WORM en Cloud Volumes ONTAP funciona bajo un modelo de "administrador de almacenamiento de confianza". Mientras que los archivos WORM se protegen de la modificación o la modificación, un administrador de clúster puede eliminar los volúmenes incluso si contienen datos WORM no vencidos.
* Además del modelo de administrador de almacenamiento de confianza, el almacenamiento WORM en Cloud Volumes ONTAP también funciona de forma implícita con un modelo de "administrador de cloud de confianza". Un administrador de cloud podría eliminar DATOS WORM antes de su fecha de caducidad si lo quita o edita directamente del proveedor de cloud.


.Enlace relacionado
* link:reference-worm-snaplock.html["Crear copias Snapshot a prueba de manipulación para el ALMACENAMIENTO WORM"]

