---
sidebar: sidebar 
permalink: concept-azure-mktplace-direct.html 
keywords: azure marketplace direct, cvo in azure marketplace 
summary:  
---
= Obtenga información acerca de las opciones de puesta en marcha de Cloud Volumes ONTAP en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp proporciona dos opciones para poner en marcha Cloud Volumes ONTAP en Azure. Tradicionalmente, Cloud Volumes ONTAP confía en BlueXP  para la puesta en marcha y la orquestación. A partir de Cloud Volumes ONTAP 9.16.1, puede aprovechar la puesta en marcha directa de Azure Marketplace, un proceso optimizado que proporciona acceso a un conjunto limitado, pero aún potente, de funciones y opciones de Cloud Volumes ONTAP.

Cuando implementa Cloud Volumes ONTAP directamente desde Azure Marketplace, no es necesario configurar el conector BlueXP  ni cumplir con otros criterios de seguridad e incorporación necesarios para poner en marcha Cloud Volumes ONTAP a través de BlueXP . Desde Azure Marketplace, puedes poner en marcha Cloud Volumes ONTAP rápidamente con unos pocos clics y explorar las funciones y funcionalidades principales de tu entorno.

Al completar la implementación en Azure Marketplace, puede descubrir estos sistemas en BlueXP . Tras la detección, puede gestionarlos como entornos de trabajo y aprovechar todas las funcionalidades de BlueXP . Consulte link:task-deploy-cvo-azure-mktplc.html["Descubra los sistemas implementados en BlueXP "].

Aquí está la comparación de características entre las dos opciones. Tenga en cuenta que las características de una instancia independiente implementada a través de Azure Marketplace cambian cuando se detecta en BlueXP .

[cols="3*"]
|===
|  | Mercado de Azure | BlueXP 


| *Onboarding* | Es más corto y fácil y se requiere una preparación mínima para una puesta en marcha directa | Proceso de incorporación más prolongado, incluida la instalación del conector BlueXP  


| *Tipos de máquinas virtuales (VM) compatibles*  a| 
Tipos de instancia EDS_v5 y LS_v3


NOTE: El tipo de instancia L8S_v3 es compatible con Azure Marketplace para configuraciones de alta disponibilidad, pero no con BlueXP . BlueXP  no podrá detectarlo correctamente durante la detección.
| Gama completa de tipos de máquinas virtuales. https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configuraciones compatibles en Azure"^] 


| *Licencia* | Licencia GRATUITA | Cualquier licencia basada en la capacidad. link:concept-licensing.html["Licencias de Cloud Volumes ONTAP"] 


| *Soporte NetApp* | No incluido | Disponible, según el tipo de licencia 


| *Capacidad* | Hasta 500 GiB | Ampliable por configuración 


| *Modelo de implementación* | Puesta en marcha del modo de alta disponibilidad (HA) en una única zona de disponibilidad (AZ) | Todas las configuraciones compatibles, incluidos los modos de nodo único y alta disponibilidad, implementaciones de una o varias zonas de disponibilidad 


| *Tipo de disco soportado* | Discos gestionados Premium SSD v2 | Mayor sujeción. link:concept-storage.html#azure-storage["Configuración predeterminada de Cloud Volumes ONTAP"] 


| *Velocidad de escritura (modo de escritura rápida)* | No admitido | Compatible, según su configuración. link:concept-write-speed.html["Obtenga información sobre las velocidades de escritura en Cloud Volumes ONTAP"]. 


| * Capacidades de orquestación* | No disponible | Disponible a través de BlueXP , en función del tipo de licencia 


| *Número de VM de almacenamiento soportadas* | Uno por puesta en marcha | Varios equipos virtuales de almacenamiento, según su configuración. link:task-managing-svms-azure.html#supported-number-of-storage-vms["Número admitido de máquinas virtuales de almacenamiento"] 


| *Cambiando el tipo de instancia* | No admitido | Compatible 


| *FabricPool tiering* | No admitido | Compatible 
|===
.Enlaces relacionados
* Implementación directa de Azure Marketplace: link:task-deploy-cvo-azure-mktplc.html["Ponga en marcha Cloud Volumes ONTAP desde Azure Marketplace"]
* Instalación de BlueXP : link:task-getting-started-azure.html["Inicio rápido para Cloud Volumes ONTAP en Azure"]
* https://docs.netapp.com/us-en/bluexp-family/index.html["Documentación de BlueXP"^]

