---
sidebar: sidebar 
permalink: concept-licensing.html 
keywords: 'freemium, professional, essentials, licensing, licenses, cloud volumes ontap charging, cloud volumes ontap licenses, cloud volumes ontap licensing, cvo licenses, cvo licensing, byol, bring your own license, paygo, pay as you go, keystone flex, keystone, cloud backup, digital wallet, bluexp license conversion for node based, license end of support (EOS) node-based, end of availability (EOA) of node-based' 
summary: Hay varias opciones de licencia disponibles para Cloud Volumes ONTAP. Cada opción le permite elegir una configuración que cumpla sus necesidades. 
---
= Licencias de Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Hay varias opciones de licencia disponibles para Cloud Volumes ONTAP. Cada opción le permite elegir un modelo de consumo que cumpla sus necesidades.



== Información general sobre las licencias

Los nuevos clientes disponen de las siguientes opciones de licencia.

Licencias basadas en capacidad:: Pague por los múltiples sistemas de Cloud Volumes ONTAP de su cuenta de NetApp mediante la capacidad aprovisionada. Incluye la capacidad de adquirir servicios de datos en cloud adicionales.
Suscripción a Keystone:: Un servicio basado en suscripciones de pago por crecimiento que ofrece una experiencia de nube híbrida fluida para pares de alta disponibilidad.


En las siguientes secciones se ofrecen más detalles acerca de cada una de estas opciones.


NOTE: No hay soporte disponible para el uso de funciones con licencia sin una licencia.



== Licencias basadas en capacidad

Los paquetes de licencias basados en la capacidad le permiten pagar por Cloud Volumes ONTAP por TIB de capacidad. La licencia está asociada con su cuenta de NetApp y le permite cargar varios sistemas con la licencia, siempre que haya suficiente capacidad disponible mediante la licencia.

Por ejemplo, podría comprar una única licencia de 20 TIB, poner en marcha cuatro sistemas de Cloud Volumes ONTAP y luego asignar un volumen de 5 TIB a cada sistema, para un total de 20 TIB. La capacidad está disponible para los volúmenes en cada sistema Cloud Volumes ONTAP implementado en esa cuenta.

La licencia basada en la capacidad está disponible en forma de un _package_. Al implementar un sistema Cloud Volumes ONTAP, puede elegir entre varios paquetes de licencias en función de las necesidades de su empresa.


NOTE: Mientras que el uso y la medición reales de los productos y servicios gestionados en BlueXP siempre se calculan en GiB y TiB, los términos GB/GiB y TB/TiB se utilizan indistintamente. Esto se refleja en las listas de Cloud Marketplace, las cotizaciones de precios, las descripciones de las listas y en otra documentación de apoyo.



=== Paquetes

Los siguientes paquetes basados en capacidad están disponibles para Cloud Volumes ONTAP.

Para obtener una lista de los tipos de máquinas virtuales admitidos con los siguientes paquetes basados en capacidad, consulte:

ifdef::azure[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Configuraciones compatibles en Azure"^]


endif::azure[]

ifdef::gcp[]

* link:https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configuraciones compatibles en Google Cloud"^]


endif::gcp[]



==== Freemium

Ofrece todas las características de Cloud Volumes ONTAP de forma gratuita desde NetApp (todavía se aplican cargos de proveedores de cloud).

* No se necesita licencia ni contrato.
* No se incluye el soporte de NetApp.
* Está limitado a 500 GIB de capacidad aprovisionada por sistema Cloud Volumes ONTAP.
* Puede usar hasta 10 sistemas Cloud Volumes ONTAP con la oferta de Freemium por cuenta de NetApp en cualquier proveedor de cloud.
* Si la capacidad aprovisionada para un sistema de Cloud Volumes ONTAP supera los 500 GIB, BlueXP convierte el sistema al paquete Essentials.
+
En cuanto un sistema se convierte al paquete Essentials, el <<Notas sobre la carga,carga mínima>> aplicable.

+
Cualquier otro sistema que tenga menos de 500 GIB de capacidad aprovisionada permanece en Freemium (siempre que se hayan desplegado utilizando la oferta Freemium).





==== Aspectos básicos

Puede pagar por capacidad en una serie de configuraciones diferentes:

* Elija la configuración de Cloud Volumes ONTAP:
+
** Un sistema de alta disponibilidad o nodo único
** Almacenamiento de archivos y bloques o datos secundarios para recuperación ante desastres (DR)


* Añada cualquiera de los servicios de datos en el cloud de NetApp por un coste adicional


Para obtener más información, consulte link:licensing-charging.html["Cargo por licencias basadas en capacidad"].



==== Optimizado

Pague por separado la capacidad aprovisionada y las operaciones de I/o.

* Nodo único de Cloud Volumes ONTAP o alta disponibilidad
* La carga se basa en dos componentes de coste: Almacenamiento y uso (I/O).
+
No le cobrarán por el I/O relacionado con la replicación de datos (SnapMirror), los backups (SnapVault) o NDMP.



ifdef::azure[]

* Disponible en Azure Marketplace como oferta de pago por uso o como contrato anual


endif::azure[]

ifdef::gcp[]

* Disponible en Google Cloud Marketplace como oferta de pago por uso o como contrato anual


endif::gcp[]

* Añada cualquiera de los servicios de datos en el cloud de NetApp por un coste adicional




==== Profesional

Pague por capacidad por cualquier tipo de configuración de Cloud Volumes ONTAP con backups ilimitados.

* Ofrece licencias para cualquier configuración de Cloud Volumes ONTAP
+
Un solo nodo o ha con carga de capacidad para volúmenes principales y secundarios al mismo ritmo

* Incluye backups de volúmenes ilimitados mediante backup y recuperación de BlueXP, pero solo para sistemas Cloud Volumes ONTAP que utilicen el paquete Professional.
+

NOTE: Se necesita una suscripción de pago por uso (PAYGO) para las funciones de backup y recuperación de BlueXP . Sin embargo, no se incurrirá en cargo por usar este servicio. Si quiere más información sobre cómo configurar la licencia para la copia de seguridad y recuperación de BlueXP , consulte https://docs.netapp.com/us-en/bluexp-backup-recovery/task-licensing-cloud-backup.html["Configura las licencias para el backup y la recuperación de BlueXP"^] .

* Añada cualquiera de los servicios de datos en el cloud de NetApp por un coste adicional




=== Cómo comenzar

Descubra cómo empezar a utilizar las licencias basadas en capacidad:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure las licencias para Cloud Volumes ONTAP en AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure las licencias para Cloud Volumes ONTAP en Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure las licencias para Cloud Volumes ONTAP en Google Cloud"]


endif::gcp[]



== Suscripción a Keystone

Un servicio basado en suscripción de pago por crecimiento que ofrece una experiencia fluida de cloud híbrido para aquellos que prefieran los modelos de consumo de gastos operativos como arrendamiento o gastos de capital iniciales.

La carga se basa en el tamaño de la capacidad comprometida de una o varias parejas de alta disponibilidad de Cloud Volumes ONTAP en su suscripción Keystone.

La capacidad aprovisionada para cada volumen se agrega y se compara con la capacidad comprometida de tu suscripción de Keystone periódicamente; los excesos se cobran como picos de potencia en tu suscripción de Keystone.

link:https://docs.netapp.com/us-en/keystone-staas/index.html["Obtenga más información acerca de NetApp Keystone"^].



=== Configuraciones admitidas

Las suscripciones de Keystone son compatibles con parejas de alta disponibilidad. Esta opción de licencia no es compatible por el momento con los sistemas de un solo nodo.



=== Límite de capacidad

Cada sistema individual de Cloud Volumes ONTAP admite hasta 2 PIB de capacidad mediante discos y organización en niveles en el almacenamiento de objetos.



=== Cómo comenzar

Descubre cómo empezar a usar una suscripción a Keystone:

ifdef::aws[]

* link:task-set-up-licensing-aws.html["Configure las licencias para Cloud Volumes ONTAP en AWS"]


endif::aws[]

ifdef::azure[]

* link:task-set-up-licensing-azure.html["Configure las licencias para Cloud Volumes ONTAP en Azure"]


endif::azure[]

ifdef::gcp[]

* link:task-set-up-licensing-google.html["Configure las licencias para Cloud Volumes ONTAP en Google Cloud"]


endif::gcp[]



== Licenciamiento por nodos

La licencia basada en nodos es el modelo de licencia de la generación anterior que le permitió obtener licencias de Cloud Volumes ONTAP por nodo. Este modelo de licencia no está disponible para nuevos clientes. La carga por nodos se ha sustituido por los métodos de carga por capacidad descritos anteriormente.

NetApp ha planificado el fin de la disponibilidad (EOA) y el soporte (EOS) de la licencia basada en nodos. Tras el EOA y la EOS, las licencias basadas en nodos deberán convertirse en licencias basadas en capacidad.

Para obtener más información, consulte https://mysupport.netapp.com/info/communications/CPC-00589.html["Comunicado del cliente: CPC-00589"^].



=== Fin de la disponibilidad de las licencias basadas en nodos

A partir del 11 de noviembre de 2024, se finalizó la disponibilidad limitada de las licencias basadas en nodos. La compatibilidad con licencias basadas en nodos finaliza el 31 de diciembre de 2024.

Si tiene un contrato válido basado en nodos que se extiende más allá de la fecha EOA, puede continuar utilizando la licencia hasta que el contrato caduque. Una vez que el contrato caduque, será necesario realizar la transición al modelo de licencias basado en capacidad. Si no tiene un contrato a largo plazo para un nodo Cloud Volumes ONTAP, es importante planificar la conversión antes de la fecha de EOS.

Obtenga más información sobre cada tipo de licencia y el impacto de EOA en él en esta tabla:

[cols="2*"]
|===
| Tipo de licencia | Impacto después de EOA 


 a| 
Licencia válida basada en nodos adquirida a través de BYOL
 a| 
La licencia sigue siendo válida hasta el vencimiento. Las licencias existentes basadas en nodos sin utilizar se pueden utilizar para poner en marcha nuevos sistemas Cloud Volumes ONTAP.



 a| 
Se adquirió una licencia basada en nodos caducada a través de su licencia BYOL
 a| 
No tendrá derecho a implementar nuevos sistemas de Cloud Volumes ONTAP con esta licencia. Es posible que los sistemas existentes sigan funcionando, pero no recibirá asistencia ni actualizaciones para sus sistemas posteriores a la fecha de EOS.



 a| 
Licencia basada en nodos válida con suscripción PAYGO
 a| 
Dejará de recibir soporte de NetApp después de la fecha de EOS, hasta que realice la transición a una licencia basada en capacidad.

|===
.Exclusiones
NetApp reconoce que determinadas situaciones requieren un consideración especial y que la disponibilidad de licencias basadas en nodos no se aplicará a los siguientes casos:

* Clientes de USPS
* Se implementa en modo privado
* Implementaciones en la región de China de Cloud Volumes ONTAP en AWS


En estos escenarios particulares, NetApp ofrecerá soporte para abordar los requisitos de licencias únicos de conformidad con las obligaciones contractuales y las necesidades operativas.


NOTE: Incluso en estos escenarios, las nuevas licencias basadas en nodos y las renovaciones de licencias son válidas por un máximo de un año a partir de la fecha de aprobación.



== Conversión de licencias

BlueXP  permite una conversión fluida de licencias basadas en nodos a capacidad basada en la herramienta de conversión de licencias. Para obtener más información sobre el fin de disponibilidad de las licencias basadas en nodos, consulte link:/concept-licensing.html#end-of-availability-of-node-based-licenses["Fin de la disponibilidad de las licencias basadas en nodos"].

Antes de realizar la transición, es bueno familiarizarse con la diferencia que existe entre los dos modelos de licencia. Las licencias basadas en nodos incluyen capacidad fija para cada instancia de ONTAP, lo que puede restringir la flexibilidad. Por otro lado, las licencias basadas en la capacidad permiten un conjunto compartido de almacenamiento en varias instancias, lo que ofrece una mayor flexibilidad, optimiza el uso de recursos y reduce la posibilidad de sanciones financieras al redistribuir las cargas de trabajo. La carga basada en la capacidad se ajusta sin problemas a los cambios en los requisitos de almacenamiento.

Para saber cómo puede realizar esta conversión, consulte link:task-convert-node-capacity.html["Convierta licencias basadas en nodos a basadas en capacidad"].


NOTE: No se admite la conversión de un sistema de la licencia basada en capacidad a la basada en nodos.
