---
sidebar: sidebar 
permalink: task-managing-svms-azure.html 
keywords: storage virtual machine, vserver, svm, storage vm, supported number, number supported 
summary: Una máquina virtual de almacenamiento es un equipo virtual que se ejecuta en ONTAP y proporciona servicios de datos y almacenamiento a sus clientes. Puede que lo sepa como una SVM o un Vserver. Cloud Volumes ONTAP se configura con una máquina virtual de almacenamiento de forma predeterminada, pero algunas configuraciones admiten máquinas virtuales de almacenamiento adicionales. 
---
= Gestione máquinas virtuales de almacenamiento que sirven datos para Cloud Volumes ONTAP en Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una máquina virtual de almacenamiento es un equipo virtual que se ejecuta en ONTAP y proporciona servicios de datos y almacenamiento a sus clientes. Puede que lo sepa como un _SVM_ o un _vserver_. Cloud Volumes ONTAP está configurado con una máquina virtual de almacenamiento de forma predeterminada, pero usted puede crear máquinas virtuales de almacenamiento adicional al ejecutar Cloud Volumes ONTAP en Azure.

Para crear y gestionar máquinas virtuales de almacenamiento que proporcionan servicios de datos adicionales en Azure, debería usar las API de BlueXP . Esto se debe a que las API automatizan el proceso de crear máquinas virtuales de almacenamiento y configurar las interfaces de red necesarias. Al crear los equipos virtuales de almacenamiento, BlueXP  configura los servicios LIF necesarios, así como la LIF iSCSI necesaria para las comunicaciones SMB/CIFS de salida desde el equipo virtual de almacenamiento.

Para obtener información sobre la ejecución de llamadas a la API de Cloud Volumes ONTAP, consulte https://docs.netapp.com/us-en/bluexp-automation/cm/your_api_call.html#step-1-select-the-identifie["Su primera llamada API"^] .



== Número admitido de máquinas virtuales de almacenamiento

A partir de Cloud Volumes ONTAP 9,9.0, según su licencia, varios equipos virtuales de almacenamiento son compatibles con configuraciones específicas. Consulte el https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-limits-azure.html["Notas de la versión de Cloud Volumes ONTAP"^] para comprobar cuál es el número de máquinas virtuales de almacenamiento admitido para su versión de Cloud Volumes ONTAP.

Todas las versiones de Cloud Volumes ONTAP anteriores a la 9.9.0 admiten una máquina virtual de almacenamiento que sirve datos y una VM de almacenamiento de destino utilizada para la recuperación ante desastres. Puede activar la máquina virtual de almacenamiento de destino para acceder a los datos si se produce una interrupción en la máquina virtual de almacenamiento de origen.



== Cree una máquina virtual de almacenamiento

En función de su configuración y el tipo de licencia, puede crear varias máquinas virtuales de almacenamiento en un sistema de un solo nodo o en una configuración de alta disponibilidad (HA) mediante las API de BlueXP .

.Acerca de esta tarea
Cuando crea máquinas virtuales de almacenamiento mediante las API y configura las interfaces de red requeridas, BlueXP  también modifica las `default-data-files` políticas en las máquinas virtuales de almacenamiento de datos. Para ello, elimina los siguientes servicios de la LIF de datos del NAS y los añade a la LIF de datos de iSCSI que se usa para las conexiones de gestión de salida:

* `data-fpolicy-client`
* `management-ad-client`
* `management-dns-client`
* `management-ldap-client`
* `management-nis-client`


.Antes de empezar
El conector requiere permisos específicos para crear máquinas virtuales de almacenamiento para Cloud Volumes ONTAP. Los permisos necesarios se incluyen en https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["Las políticas proporcionadas por NetApp"^].



=== Sistema de un solo nodo

Utilice la siguiente llamada API para crear una máquina virtual de almacenamiento en un sistema de nodo único.

`POST /azure/vsa/working-environments/{workingEnvironmentId}/svm`

Incluya los siguientes parámetros en el cuerpo de la solicitud:

[source, json]
----
{ "svmName": "myNewSvm1"
   "svmPassword": "optional, the API takes the cluster password if not provided"
   "mgmtLif": "optional, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


=== Pareja de HA

Use la siguiente llamada API para crear una máquina virtual de almacenamiento en un par de alta disponibilidad:

`POST /azure/ha/working-environments/{workingEnvironmentId}/svm`

Incluya los siguientes parámetros en el cuerpo de la solicitud:

[source, json]
----
{ "svmName": "NewSvmName"
   "svmPassword": "optional value, the API takes the cluster password if not provided"
   "mgmtLif": "optional value, to create an additional management LIF, if you want to use the storage VM for management purposes"}
----


== Gestione máquinas virtuales de almacenamiento en sistemas de nodo único y pares de alta disponibilidad

Mediante las API de BlueXP  puede cambiar el nombre y eliminar máquinas virtuales de almacenamiento tanto en configuraciones de nodo único como de alta disponibilidad.

.Antes de empezar
El conector requiere permisos específicos para gestionar las máquinas virtuales de almacenamiento de Cloud Volumes ONTAP. Los permisos necesarios se incluyen en https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html["Las políticas proporcionadas por NetApp"^].



=== Cambiar el nombre a una máquina virtual de almacenamiento

Para cambiar el nombre de una máquina virtual de almacenamiento, debe proporcionar los nombres de la máquina virtual de almacenamiento existente y la nueva máquina virtual de almacenamiento como parámetros.

.Pasos
* Utilice la siguiente llamada API para cambiar el nombre de una máquina virtual de almacenamiento en un sistema de nodo:
+
`PUT /azure/vsa/working-environments/{workingEnvironmentId}/svm`

+
Incluya los siguientes parámetros en el cuerpo de la solicitud:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----
* Use la siguiente llamada API para cambiar el nombre de una máquina virtual de almacenamiento en una pareja de alta disponibilidad:
+
`PUT /azure/ha/working-environments/{workingEnvironmentId}/svm`

+
Incluya los siguientes parámetros en el cuerpo de la solicitud:

+
[source, json]
----
{
  "svmNewName": "NewSvmName",
  "svmName": "OldSvmName"
}
----




=== Eliminar una máquina virtual de almacenamiento

En un único nodo o en una configuración de alta disponibilidad, puede quitar una máquina virtual de almacenamiento si no tiene volúmenes activos.

.Pasos
* Use la siguiente llamada API para eliminar una máquina virtual de almacenamiento en un sistema de nodo:
+
`DELETE /azure/vsa/working-environments/{workingEnvironmentId}/svm/{svmName}`

* Use la siguiente llamada API para eliminar una máquina virtual de almacenamiento en un par de alta disponibilidad:
+
`DELETE /azure/ha/working-environments/{workingEnvironmentId}/svm/{svmName}`



.Información relacionada
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Prepare el uso de la API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Flujos de trabajo de Cloud Volumes ONTAP"^]

