---
sidebar: sidebar 
permalink: task-convert-node-capacity.html 
keywords: license conversion, convert node-based to capacity based, by-node to by-capacity, bluexp license conversion for node based 
summary: 'Tras el fin de la disponibilidad (EOA) de sus licencias basadas en nodos, debe realizar la transición a licencias basadas en capacidad mediante la herramienta de conversión de licencias BlueXP .' 
---
= Convierta una licencia basada en nodos de Cloud Volumes ONTAP en una licencia basada en capacidad
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Tras el fin de la disponibilidad (EOA) de sus licencias basadas en nodos, debe realizar la transición a licencias basadas en capacidad mediante la herramienta de conversión de licencias BlueXP .

Para compromisos anuales o a más largo plazo, NetApp recomienda que se ponga en contacto con su representante de NetApp antes de la fecha de fin de disponibilidad (11 de noviembre de 2024) o de la fecha de vencimiento de la licencia para garantizar que se cumplen los requisitos previos para la transición. Si no tiene un contrato a largo plazo para un nodo de Cloud Volumes ONTAP y su sistema se ejecuta con una suscripción de pago por uso bajo demanda (PAYGO), es importante que se planifique la conversión antes de la finalización del soporte (EOS) del 31 de diciembre de 2024. En ambos casos, debe asegurarse de que su sistema cumple los requisitos antes de utilizar la herramienta de conversión de licencias de BlueXP  para una transición sin problemas.

Para obtener más información acerca de EOA y EOS, consulte link:concept-licensing.html#end-of-availability-of-node-based-licenses["Fin de la disponibilidad de las licencias basadas en nodos"].

.Acerca de esta tarea
* Cuando utiliza la herramienta de conversión de licencias, la transición del modelo de licencias basado en nodos al basado en capacidad se realiza in situ y en línea, lo que elimina la necesidad de migrar datos o aprovisionar recursos de cloud adicionales.
* Es una operación no disruptiva y no se produce ninguna interrupción del servicio ni tiempo de inactividad de las aplicaciones.
* Los datos de cuenta y aplicaciones de su sistema Cloud Volumes ONTAP permanecen intactos.
* Los recursos de cloud subyacentes no se ven afectados después de la conversión.
* La herramienta de conversión de licencias admite todos los tipos de implementación, como nodo único, alta disponibilidad (HA) en una sola zona de disponibilidad (AZ), alta disponibilidad en varias zonas, BYOL (BYOL) y PAYGO.
* La herramienta admite todas las licencias basadas en nodos como origen y todas las licencias basadas en capacidad como destino. Por ejemplo, si tiene una licencia PAYGO Standard basada en nodos, puede convertirla a cualquier licencia basada en capacidad adquirida a través del marketplace. NetApp ha restringido la compra, extensión y renovación de licencias BYOL. Para obtener más información, consulte  https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilidad restringida de licencias BYOL para Cloud Volumes ONTAP"^] .
* La conversión es compatible con todos los proveedores de cloud, AWS, Azure y Google Cloud.
* Después de la conversión, el número de serie de la licencia basada en nodos será reemplazado por un formato basado en capacidad. Esto se realiza como parte de la conversión y se refleja en su cuenta del sitio de soporte de NetApp (NSS).
* Cuando realice la transición al modelo basado en capacidad, sus datos seguirán conservándose en la misma ubicación que la licencia basada en nodos. Este enfoque no garantiza interrupciones en la ubicación de los datos y mantiene los principios de soberanía de datos durante la transición.


.Antes de empezar
* Debe tener una cuenta de NSS con acceso de cliente o de administrador.
* Su cuenta de NSS debe registrarse con las credenciales de usuario de BlueXP .
* El entorno de trabajo debe estar vinculado a la cuenta NSS con acceso de cliente o acceso de administrador.
* Debe tener una licencia válida basada en la capacidad, ya sea una licencia de BYOL o una suscripción del mercado.
* Debe haber una licencia basada en capacidad disponible en la cuenta de BlueXP . Esta licencia puede ser una suscripción al mercado o un paquete de oferta BYOL/privada en la cartera digital de BlueXP .
* Antes de seleccionar un paquete de destino, tenga en cuenta los siguientes criterios:
+
** Si la cuenta tiene una licencia BYOL basada en la capacidad, el paquete de destino seleccionado debe alinearse con las licencias basadas en capacidad de BYOL de la cuenta:
+
*** Cuando `Professional` se selecciona como paquete de destino, la cuenta debe tener una licencia BYOL con un paquete Professional:
*** Cuando `Essentials` se selecciona como el paquete de destino, la cuenta debe tener una licencia BYOL con el paquete Essentials.
*** Cuando `Optimized` se selecciona como paquete de destino, la cuenta debe tener una licencia BYOL con el paquete optimizado.


** Si el paquete de destino no se alinea con la disponibilidad de licencia BYOL de la cuenta, significa que la licencia basada en capacidad podría no incluir el paquete seleccionado. En este caso, se le cobrará a través de su suscripción a Marketplace.
** Si no existe ninguna licencia BYOL basada en la capacidad sino solo una suscripción del mercado, debe asegurarse de que el paquete seleccionado esté incluido en su suscripción al mercado basado en la capacidad.
** Si no hay capacidad suficiente en su licencia actual basada en capacidad y si tiene una suscripción del mercado para cobrar por el uso de capacidad adicional, se le cobrará la capacidad adicional a través de su suscripción al mercado.
** Si no hay capacidad suficiente en su licencia actual basada en capacidad y no tiene una suscripción del mercado para cobrar por el uso de capacidad adicional, no se puede realizar la conversión. Debe agregar una suscripción de Marketplace para cargar la capacidad adicional o ampliar la capacidad disponible a su licencia actual.
** Si el paquete de destino no se alinea con la disponibilidad de la licencia BYOL de la cuenta y también si no hay capacidad suficiente en la licencia existente basada en capacidad, se le cobrará a través de la suscripción al mercado.





NOTE: Si alguno de estos requisitos no se cumple, la conversión de licencia no se produce. En casos específicos, la licencia puede ser convertida, pero no puede ser utilizada. Haga clic en el icono de información para identificar los problemas y realizar acciones correctivas.

.Pasos
. En la página Lienzo, haga doble clic en el nombre del entorno de trabajo para el que desea modificar el tipo de licencia.
. En la pestaña Descripción general, haga clic en el panel Operaciones.
. Compruebe el icono del lápiz junto a *Método de carga*. Si el método de carga del sistema es `Node Based`, puede convertirlo en carga por capacidad.
+

TIP: El icono se desactiva si el sistema Cloud Volumes ONTAP ya está cargado por capacidad o si alguno de los requisitos no se cumple.

. En la pantalla *Convertir licencias basadas en nodos a basadas en capacidad*, verifique el nombre del entorno de trabajo y los detalles de la licencia de origen.
. Seleccione el paquete de destino para convertir la licencia existente:
+
** Aspectos básicos. El valor predeterminado es `Essentials`.
** Profesional




ifdef::azure[]

* Optimizado (para Azure)


endif::azure[]

ifdef::gcp[]

* Optimizado (para Google Cloud)


endif::gcp[]

. Si tiene una licencia BYOL, puede marcar la casilla de verificación para eliminar la licencia basada en nodo de la cartera digital de BlueXP  después de la conversión. Si la conversión no se completa, incluso al seleccionar esta casilla de verificación, la licencia no se eliminará de la cartera digital. Si tiene una suscripción a Marketplace, esta opción no está disponible.
. Seleccione la casilla de verificación para confirmar que comprende las implicaciones del cambio y, a continuación, haga clic en * Continuar *.


.Después de terminar
Vea el número de serie de la nueva licencia y verifique los cambios en la cartera digital de BlueXP .
