---
sidebar: sidebar 
permalink: task-google-key-manager.html 
keywords: google cloud, encryption, NVE, NetApp volume encryption, KMIP, GCP, GCP KMS, key manager service, encryption 
summary: Utilice el servicio de gestión de claves de Google para su servicio de gestión de claves de terceros. 
---
= Gestione las claves de cifrado de Cloud Volumes ONTAP con KMS de Google Cloud
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Puedes usar link:https://cloud.google.com/kms/docs["Servicio de gestión de claves de Google Cloud Platform (Cloud KMS)"^] para proteger tus claves de cifrado de Cloud Volumes ONTAP en una aplicación implementada por Google Cloud Platform.

La gestión de claves con Cloud KMS se puede habilitar con la interfaz de línea de comandos de ONTAP o la API DE REST de ONTAP.

Al usar Cloud KMS, tenga en cuenta que, de forma predeterminada, se usa LIF de una SVM de datos para comunicarse con el punto final de la gestión de claves de cloud. Una red de gestión de nodos se usa para comunicarse con los servicios de autenticación del proveedor de cloud (oauth2.googleapis.com). Si la red de clúster no está configurada correctamente, el clúster no utilizará correctamente el servicio de gestión de claves.

.Antes de empezar
* Su sistema debe ejecutar Cloud Volumes ONTAP 9.10.1 o posterior
* Debe usar un SVM de datos. Cloud KMS solo se puede configurar en un SVM de datos.
* Debe ser un administrador de clústeres o SVM
* La licencia de cifrado de volumen (VE) debe estar instalada en el SVM
* A partir de Cloud Volumes ONTAP 9.12.1 GA, también se debe instalar la licencia de administración de claves de cifrado multiinquilino (MTEKM)
* Se requiere una suscripción activa a Google Cloud Platform




== Configuración

.Google Cloud
. En su entorno de Google Cloud, link:https://cloud.google.com/kms/docs/creating-keys["Cree una clave y un anillo de clave de GCP simétrico"^].
. Asigne una función personalizada a la clave Cloud KMS y a la cuenta de servicio Cloud Volumes ONTAP.
+
.. Crea el rol personalizado:
+
[listing]
----
gcloud iam roles create kmsCustomRole
    --project=<project_id>
    --title=<kms_custom_role_name>
    --description=<custom_role_description>
    --permissions=cloudkms.cryptoKeyVersions.get,cloudkms.cryptoKeyVersions.list,cloudkms.cryptoKeyVersions.useToDecrypt,cloudkms.cryptoKeyVersions.useToEncrypt,cloudkms.cryptoKeys.get,cloudkms.keyRings.get,cloudkms.locations.get,cloudkms.locations.list,resourcemanager.projects.get
    --stage=GA
----
.. Asigna el rol personalizado que creaste: 
`gcloud kms keys add-iam-policy-binding _key_name_ --keyring _key_ring_name_ --location _key_location_ --member serviceAccount:_service_account_Name_ --role projects/_customer_project_id_/roles/kmsCustomRole`
+

NOTE: Si utiliza Cloud Volumes ONTAP 9.13.0 o una versión posterior, no necesita crear un rol personalizado. Puede asignar el rol predefinido. [`cloudkms.cryptoKeyEncrypterDecrypter` ^] papel.



. Descargue la clave JSON de la cuenta de servicio:
`gcloud iam service-accounts keys create key-file --iam-account=_sa-name_@_project-id_.iam.gserviceaccount.com`


.Cloud Volumes ONTAP
. Conéctese a la LIF de gestión de clústeres con el cliente SSH preferido.
. Cambie al nivel de privilegio avanzado:
`set -privilege advanced`
. Cree un DNS para la SVM de datos.
`dns create -domains c._<project>_.internal -name-servers _server_address_ -vserver _SVM_name_`
. Crear entrada CMEK:
`security key-manager external gcp enable -vserver _SVM_name_ -project-id _project_ -key-ring-name _key_ring_name_ -key-ring-location _key_ring_location_ -key-name _key_name_`
. Cuando se le solicite, introduzca la clave JSON de la cuenta de servicio desde su cuenta de GCP.
. Confirme que el proceso activado se ha realizado correctamente:
`security key-manager external gcp check -vserver _svm_name_`
. OPCIONAL: Cree un volumen para probar el cifrado `vol create _volume_name_ -aggregate _aggregate_ -vserver _vserver_name_ -size 10G`




== Solucionar problemas

Si necesita solucionar problemas, puede cola los registros de la API DE REST sin configurar en los dos últimos pasos que se indican a continuación:

. `set d`
. `systemshell -node _node_ -command tail -f /mroot/etc/log/mlog/kmip2_client.log`

