---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Cloud Volumes ONTAP utiliza un enlace privado de Azure para las conexiones a sus cuentas de almacenamiento asociadas. Si es necesario, puede deshabilitar los vínculos privados de Azure y usar extremos de servicio en su lugar. 
---
= Configure la creación de grupos de ubicaciones para los pares de alta disponibilidad de Cloud Volumes ONTAP en los AZs únicos de AWS
:allow-uri-read: 


[role="lead"]
Las implementaciones de alta disponibilidad (HA) de Cloud Volumes ONTAP en la zona de disponibilidad única (AZ) de AWS pueden fallar y revertirse en caso de que se produzca un error en la creación del grupo de colocación. La creación del grupo de colocación también falla y el despliegue retrocede si el nodo de Cloud Volumes ONTAP y la instancia de mediador no están disponibles. Para evitar esto, puede modificar la configuración para permitir que el despliegue finalice incluso si falla la creación del grupo de colocación.

Al omitir el proceso de rollback, el proceso de despliegue de Cloud Volumes ONTAP finaliza correctamente y le notifica que la creación del grupo de colocación está incompleta.

.Pasos
. Utilice SSH para conectarse al host del conector e iniciar sesión.
. Navegar a `/opt/application/netapp/cloudmanager/docker_occm/data`.
. Edite `app.conf` cambiando el valor del `rollback-on-placement-group-failure` parámetro a `false`. El valor por defecto de este parámetro es `true`.
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
. Guarde el archivo y cierre la sesión del conector. No es necesario reiniciar el conector.

