= Máquinas de la serie N1 no disponibles para la selección en BlueXP 
:allow-uri-read: 




=== Máquinas de la serie N1 no disponibles para la selección en BlueXP 

Las máquinas de la serie n1 ya no están disponibles para su selección en BlueXP  al implementar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 sólo se conservarán y admitirán en sistemas antiguos existentes. Las nuevas implementaciones de Cloud Volumes ONTAP solo son compatibles con Google Cloud a partir de la versión 9,8. Le recomendamos que cambie a los tipos de máquinas de la serie n2 que sean compatibles con Cloud Volumes ONTAP 9,8 y posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevas implementaciones realizadas a través de la API.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Configuraciones compatibles en Google Cloud"^].



=== Compatibilidad con las zonas locales para Amazon Web Services en modo privado

BlueXP  ahora es compatible con AWS Local Zones para puestas en marcha de alta disponibilidad de Cloud Volumes ONTAP (HA) en el modo privado. El soporte que antes estaba limitado solo al modo estándar ahora se ha ampliado para incluir el modo privado.


NOTE: Las zonas locales de AWS no se admiten cuando se utiliza BlueXP  en modo restringido.

Para obtener más información sobre las zonas locales de AWS con puestas en marcha de alta disponibilidad, consulte link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-ha.html#aws-local-zones["Zonas locales de AWS"^].
