= Detección de implementaciones realizadas a través del mercado de Azure en BlueXP 
:allow-uri-read: 




=== Detección de implementaciones realizadas a través del mercado de Azure en BlueXP 

BlueXP  ahora tiene la capacidad de detectar los sistemas Cloud Volumes ONTAP puestos en marcha directamente a través de Azure Marketplace. Esto significa que ahora puede añadir y gestionar estos sistemas como entornos de trabajo en BlueXP , al igual que cualquier otro sistema de Cloud Volumes ONTAP.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploy-cvo-azure-mktplc.html["Ponga en marcha Cloud Volumes ONTAP desde Azure Marketplace"^]



=== Capacidad de organizar datos en niveles para inquilinos de Azure

Ahora puede habilitar la organización en niveles para un inquilino de Azure en una situación en la que el entorno de trabajo de Cloud Volumes ONTAP se crea mediante un inquilino y el conector BlueXP  se crea mediante otro. Mediante esta funcionalidad, puede utilizar el mismo conector para organizar datos en niveles para múltiples inquilinos de Azure.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-tiering.html#requirements-to-tier-data-for-an-azure-tenant["Requisitos para organizar los datos en niveles para un inquilino de Azure"^]
